# Inherit base settings from https://github.com/jenkinsci/.github/blob/master/.github/release-drafter.yml
_extends: .github
name-template: REST List Parameter v$RESOLVED_VERSION
tag-template: rest-list-parameter-$RESOLVED_VERSION
version-template: $MAJOR.$MINOR.$PATCH

# Basic SemVer version resolver
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch