name: Build and Test Plugin

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3
      - name: Set up JDK 11
        uses: actions/setup-java@v1.4
        with:
          java-version: 11
      - name: Cache local Maven repository
        uses: actions/cache@v2.1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build with Maven
        run: mvn -B test --file pom.xml