name: Release Drafter

on:
  push:
    # branches to consider in the event; optional, defaults to all
    branches: [ main ]
    tags: [ '*' ]

jobs:
  update_release_draft:
    name: Update release draft
    runs-on: ubuntu-latest
    steps:
      - name: Update Release Draft
        id: draft_release
        uses: release-drafter/release-drafter@v5.11.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release_with_assets:
    name: Publish drafted release with assets
    needs: [ update_release_draft ]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build with Maven
        run: mvn -B package --file pom.xml -Dmaven.test.skip=true
      - name: Upload Release Asset to Release Draft
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.draft_release.outputs.upload_url }}
          asset_path: ./target/rest-list-parameter.hpi
          asset_name: rest-list-parameter.hpi
          asset_content_type: application/zip
      - name: Publish drafted Releas
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{ steps.draft_release.outputs.id }}
